name: Docs
on: [push, pull_request, workflow_dispatch]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install sphinx==6.1.3 sphinx_rtd_theme sphinx-favicon myst_parser sphinx_sitemap
      - name: Sphinx build
        run: |
          sphinx-build -W --keep-going doc _build
          if [ $? -ne 0 ]; then
            echo -e "\033[1;31mSphinx build FAILED\033[0m\n"
            exit 1
          else
            echo -e "\033[1;32mSphinx build PASSED\033[0m\n"
          fi
      - name: Insert HTTP redirection after 5 seconds
        run: |
          sed -i 's|</head>|    <meta http-equiv="refresh" content="5;url=https://zeiss.github.io/gom-software-python-api/2022/">\n</head>|' _build/index.html
      - name: Set branch name
        id: branch
        run: echo "SUBDIR_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Deploy
        if: ${{ github.event_name != 'pull_request' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          destination_dir: ${{ env.SUBDIR_NAME }}
          full_commit_message: Deploy documentation of '${{ env.SUBDIR_NAME }}' to GitHub Pages
